name = "Winterlands"
author = "Zacklack"
version = "0.131.8"
description = "A cozy winter and slightly Christmas-themed Modpack, perfect for the classic 2-week Minecraft phase in winter."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0446dec73690af8255293dc56b2fb18065d116f2fb663280eeefd5d46228422"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
datapack-folder = "config/paxi/datapacks"
