name = "Winterlands"
author = "Zacklack"
version = "0.131.9"
description = "A cozy winter and slightly Christmas-themed Modpack, perfect for the classic 2-week Minecraft phase in winter."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2a7cbc37c925d110d8dd04b9ef3c06059415858596b4ea0692e044cf45fad68"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
datapack-folder = "config/paxi/datapacks"
